version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"  # Expose NGINX on host port 8080
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - ./nginx/access.log:/var/log/nginx/access.log
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT:-3000}
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_network

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT:-3000}
      - APP_POOL=blue
    ports:
      - "8081:${PORT:-3000}"
    networks:
      - app_network

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT:-3000}
      - APP_POOL=green
    ports:
      - "8082:${PORT:-3000}"
    networks:
      - app_network

  alert_watcher:
    build: ./watcher
    volumes:
      - ./nginx/access.log:/var/log/nginx/access.log
    environment:
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      ERROR_RATE_THRESHOLD: "2"
      WINDOW_SIZE: "200"
      ALERT_COOLDOWN_SEC: "300"
      MAINTENANCE_MODE: "false"
    networks:
      - app_network



networks:
  app_network:
    driver: bridge
